env:
  MONGO_DB_HOST: 192.168.10.96:27017,192.168.10.97:27017
  MONGO_DB_USERNAME: websession
  MONGO_DB_PASSWD: WHsessionWEB!
  MONGO_DB_REPLICASET: ticket
  SESSION_MAX_AGE: 7200000 #2*60*60*1000
version: <%= VERSION %>